# Go
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GOBIN:  '$(system.defaultWorkingDirectory)/bin' # Go binaries path

steps:
- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'Jfrog-oidc'
    command: 'jf rt ping'
