# Go
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GOBIN:  '$(system.defaultWorkingDirectory)/bin' # Go binaries path
  JFROG_CLI_LOG_LEVEL: DEBUG

steps:
- task: JfrogCliV2@1
  name: jfStep
  inputs:
    jfrogPlatformConnection: 'azure-oidc'
    command: 'jf rt ping'

- script: |
    echo "The OIDC user is: $(jfStep.oidc_user)"
    echo "The OIDC token is is: $(jfStep.oidc_token)"
  displayName: "Echo the OIDC User"