# Go
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GOBIN:  '$(system.defaultWorkingDirectory)/bin' # Go binaries path
  JFROG_CLI_LOG_LEVEL: DEBUG

steps:
- task: JfrogCliV2@1
  name: jfStep
  inputs:
    jfrogPlatformConnection: 'azure-oidc'
    command: 'jf rt ping'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
        echo "Message variable is $(oidc_user)."
        echo "Message env variable is $env:oidc_user."
  displayName: 'Read variable'