# Go
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GOBIN:  '$(system.defaultWorkingDirectory)/bin' # Go binaries path
  JFROG_CLI_LOG_LEVEL: DEBUG

steps:
- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'azure-oidc'
    command: 'jf rt ping'
